name: Trigger SonarQube Scan

on:
  workflow_dispatch:

jobs:
  call-sonarqube-scan:
    uses: kanalabs/devops_workflow/.github/workflows/sonarqube.yaml@main
    with:
       host: ${{ secrets.SONARQUBE_HOST }}
       login: ${{ secrets.SONARQUBE_TOKEN }}
